### ISSUE TITLE
Feature request - sync status

### ISSUE THREAD

**Issue by swapper82** [qaxi/nagios-check_3par#5]
Hi!
This check is very good as it is.
But i have a feature request regarding checking if volumes are in sync.
We have had problems that rcopy groups are loosing sync.
it would be very nice if there where a option to monitor and check if the copygroups are in "synced" state and if not it would be a warning.

**Comment by qaxi** [comment]
Hello,
what commands are necesary to get status of rcopy sync?

**Comment by qaxi** [comment]
@swapper82 any update ?
