### ISSUE TITLE
error on module check_health, if LD subtype of 3par report an 'total' message

### ISSUE THREAD

**Issue by mkuerschner** [qaxi/nagios-check_3par#6]
Hi,
 we had the following condition: the 3par controller report an error on type LD. This breaks the check_health module and report an error. The word "total" is 2 time available inside the internal variable TOTAL. This raise the error on line 620. I fixed the error with an exclusion on the other "total" word group.

Line 619 original:
TOTAL=$( echo "${TMPOUT}" | grep total | awk '{print $1}' )

Line 619 fixed:
TOTAL=$( echo "${TMPOUT}" | grep -v "total node" | grep total | awk '{print $1}' )

Kind regards,
Michael

**Comment by qaxi** [comment]
solved by 0f60e3a
