### ISSUE TITLE
bug - failed grep check instead of degraded

### ISSUE THREAD

**Issue by petr-fischer** [qaxi/nagios-check_3par#7]
You need to change "grep -c failed" to "grep -c degraded", IMHO. Degraded state is now ignored in check_pd.

https://github.com/qaxi/nagios-check_3par/blob/51e5beeae62393913ddbc0f749576080a2c34ad4/check_3par#L283

Look at the original nagios script:
https://exchange.nagios.org/components/com_mtree/attachment.php?link_id=2610&cf_id=24

**Comment by qaxi** [comment]
Hi,
you are right. Thank you for notifiing.

Bugfix 396e959 and version 1.5 released .
